### ISSUE TITLE
What is the supported React version?

### ISSUE THREAD

**Issue by baldram** [react4j/react4j#37]
Hi!
Thank you for developing this interesting project.

I see a lot of dependencies is upgraded frequently. 
But there is an information which seems to be unclear to me. 
What is the supported React version at the moment? 

The only information I was able to find is in [TODO](https://github.com/react4j/react4j/blob/master/TODO.md) section. 
It was said about 16.4 and 16.5, but is also not clear whether any of mentioned ones is already supported.  

Would you please clarify?
What is the short term goal if about the React library compatibility?
Also, if recent React versions are not relevant if about React4j approach (like no real benefits for Java-way), a word of explanation why would be also very welcome.

Thank you in advance.

Best regards,
Marcin

**Comment by realityforge** [comment]
The current version we bind against is `16.6.0`. See https://github.com/react4j/react4j/blob/master/tasks/js_asset.rake#L3-L6 for where this occurs but as you may have guessed this is less relevant in react4j.

React4j essentially has a parallel component hierarchy that is more java-esque. We do this so that component developers do not have to understand how jsinterop works and so that the components can act in a way more consistent with how a java develoepr thinks. Unfortunately we don't have any real documentation around this except for some notes we made at the start of the project at [Why is there both NativeComponent and Component classes?](https://react4j.github.io/docs/faq.html#why-is-there-both-nativecomponent-and-component-classes).

We tend to move forward when there is a performance improvement or feature improvement that we want to incoporate into the java model. It is not hard to do but don't tend to do it unless there is a particular advantage.

Our current plan is to move forward to 16.8+ version when hooks cover off the complete set of uses cases that ES6 classes in react covered. Last time I checked was Error boundaries still have to be ES6 classes. When we do this we will also rework the annotation to output hooks based components rather than class based components (under the assumption that this will reduce the code size of apps as GWT/J2CL can rewrite a bunch more symbols and we will be able to omit the class infrastructure from `react.js`. Other than performance, this approach will also allow use to support multiple context values from within a single component without wrapping the component.

Other triggers for moving forward will be suspense for data being marked as stable - we are eagerly awaiting this one. Another one is if the new dev tools adds something significant that we want.

That said there is likely things that we are missing from earlier versions ... although I can't remember what they would be. I am off traveling atm but will be home in a couple of weeks and can check then. Looking through the public TODO it seems that the only stable APIs missing is `React.warn` and some profiling hooks.

HTH

**Comment by baldram** [comment]
Thank you for answer. It looks like everything is clear now. 
Best regards,
Marcin

**Comment by realityforge** [comment]
👍
