### ISSUE TITLE
Demo app is not running (maven)

### ISSUE THREAD

**Issue by baldram** [react4j/react4j#38]
Hi!
Thank you for this interesting project. 

I'm considering building an application with React4J, but at first I tried to run at least one example to see whether it works fine with my environment.

> Environment:

Mint Linux 18.3

> Relevant code or config:
> What happened:
> Problem description:
> Reproduction repository:

I tried to follow instructions and run examples from [here](https://react4j.github.io/docs/todomvc.html). 
I'm interested in Maven, Gradle or Bazel. 
Until the last one is ready, I try with the Maven example. 
It compiles fine, but when I try to run the application, something is wrong. 
(I have no issues with running  GWT stuff from different sources).

> What you did:

I take [Dagger Maven example](https://github.com/react4j/react4j-todomvc/tree/dagger_maven).

When I compile with `mvn clean compile`, it is fine. 
 ```shell
[INFO] BUILD SUCCESS
```
When I try to run: `mvn gwt:devmode` I get `BUILD FAILURE` unfortunately.
```shell
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building react4j-todomvc 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> gwt-maven-plugin:1.0-rc-9:devmode (default-cli) > process-classes @ react4j-todomvc >>>
[INFO] 
[INFO] --- gwt-maven-plugin:1.0-rc-9:enforce-encoding (default-enforce-encoding) @ react4j-todomvc ---
[INFO] 
[INFO] --- gwt-maven-plugin:1.0-rc-9:add-super-sources (default-add-super-sources) @ react4j-todomvc ---
[INFO] 
[INFO] --- gwt-maven-plugin:1.0-rc-9:add-test-super-sources (default-add-test-super-sources) @ react4j-todomvc ---
[INFO] 
[INFO] --- gwt-maven-plugin:1.0-rc-9:generate-module (default-generate-module) @ react4j-todomvc ---
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ react4j-todomvc ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO] skip non existing resourceDirectory /home/msx/workspace/java/gwt/react4j-todomvc/src/main/super
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ react4j-todomvc ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] <<< gwt-maven-plugin:1.0-rc-9:devmode (default-cli) < process-classes @ react4j-todomvc <<<
[INFO] 
[INFO] --- gwt-maven-plugin:1.0-rc-9:devmode (default-cli) @ react4j-todomvc ---
[WARNING] Error: Could not find or load main class com.google.gwt.dev.DevMode
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.906 s
[INFO] Finished at: 2019-10-27T17:51:08+01:00
[INFO] Final Memory: 15M/392M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-9:devmode (default-cli) on project react4j-todomvc: GWT exited with status 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Then I see that recent commits are Bazel related. So I tried with bazel. I switched to the related branch. Again no steps in documentation. So I tried to guess. 

When I compile, it's fine.
I do: `bazel build //:react4j_todomvc_dev` and the result is `OK`.
Further I do `bazel run //:react4j_todomvc_dev` (is this the right command?). I get an error as following:

```
ERROR: Cannot run target //:react4j_todomvc_dev: Not executable
INFO: Elapsed time: 0.162s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Maybe I do something wrong? There are no steps what to do in README, so I tried to run it as usual. 
Would you please clarify? 

Did I test my environment? 
Yes!
For instance, I take [vue-gwt-demo](https://github.com/VueGWT/vue-gwt-demo) .
I do `mvn clean compile` and I get `[INFO] BUILD SUCCESS`.
Further I do `mvn gwt:devmode` and I get 
```shell
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Vue GWT demo project 1.0-beta-9
[INFO] ------------------------------------------------------------------------
...
[INFO] Super Dev Mode starting up
...
[INFO]    Loading Java files in com.axellience.vuegwtdemo.VueGwtDemo.
[INFO]    Module setup completed in 5499 ms
[INFO] 
[INFO] The code server is ready at http://127.0.1.1:9876/
```
I see this GWT Developement Mode window and further I go to `http://127.0.1.1:8888/VueGwtDemo/` and I see the example application.
All is fine. 

> Suggested solution:

I tried to bump `gwt-maven-plugin` to the latest final and stable 1.0.0 version, but it didn't help.

Would you please suggest me where to find any simple working example for react4j?

**Comment by realityforge** [comment]
I will get the Maven example working. It is almost certainly because I misconfigured the build. We don't use Maven and I only configured the Maven build so that I could produce the optimized production builds correctly to use from integration tests (i.e. the [downstream-test](https://github.com/react4j/react4j/tree/master/downstream-test/src/main/java/react4j/downstream) module).

I have never tried the dev mode from the command line for Maven - never really known how to do it. So I will try now and get back to you. I will hopefully get it tonight otherwise I may be a few days as I am not sure my next holiday location has mobile reception ;)

**Comment by realityforge** [comment]
Ok - so you should be able to get started with `mvn -Pdev clean gwt:devmode`. This should run the app in devmode.

It should be notes that the way we tend to develop apps is with either a separate `Prod` or `Dev` suffixed GWT module so that in production we can strip out as much code as possible while in development mode we can turn on as many invariant checks as possible to catch coding errors. So I have had to use a separate `dev` profile in Maven for running dev mode. I am not sure if this is correct use of profiles in maven ... but it seems to work. It also means that if you are ever doing any performance testing make sure you use the optimized builds.

Anyhoo - I will try to write up a how-to in each of the examples demonstrating how to run the apps for each different build system.

HTH

If you have any other queries feel free to send em ;)

I will leave this issue open until I get around to writing up how-tos for examples.

**Comment by baldram** [comment]
Thank you for fast response.
After updating of my local copy with `git pull --rebase` and recompiling it using `mvn clean compile`, 
I was able to run it successfully with:
`mvn -Pdev clean gwt:devmode`. 
The DEV mode seems to work fine, I got hot swapping working.
Thank you!

Btw...
Does the experimental Bazel branch version (raw_bazel_j2cl) already works? 
If yes, what command do you use to build and run it?

**Comment by realityforge** [comment]
The `raw_bazel_j2cl` branch used to work but I it was based off of a very early alpha release of the maven j2cl plugin which is no longer available. When I am back at my desk next week I will poke around and see what it will take to get it revived. The arez+react4j works fine under j2cl or at least it used to. We previously had a reasonably large project working using that plugin.

The problem was that the build systems + j2cl were moving targets. The only problem I foresee is how to exclude `react.js` from the closure compile (I previously patched the plugin to make this work).

**Comment by baldram** [comment]
Thanks. It sounds good. I'm just a little bit excited with J2CL, but it's not something really needed for my open source project. Due to use of Maven with the Spring Boot part, it would be better to keep both using the same build system. Otherwise, I would have to move with the backend part to Bazel, but it's not yet officially supported by Pivotal. So I'm happy with Maven (the project won't be that large that I would need incremental builds). Maybe migration to Gradle in the future to get rid of XML, but this should be rather easy. So I'm really happy with what is available right now :-)

If I properly understood "holiday location", have a good holidays! ;-)

PS: Bazel and J2CL would be still some good topic to play with and further for some blog post(s) to spread this knowledge.

**Comment by realityforge** [comment]
Just got back home and added the following snippet to the README which should help anyone who is poking about in the future.

> You can build a production version of the example via `mvn clean package` which will produce a war file named `target/react4j-todomvc-1.0.0-SNAPSHOT.war` that you can deploy in any servlet container. You can also run the application locally using GWTs "devmode" via `mvn -Pdev clean gwt:devmode`. It should be noted that the devmode version of the application enables invariant checking in every library and thus will have a significant performance degradation compared to production mode.

I may poke around and see how hard it would be to get j2cl compiles working again. HTH

**Comment by baldram** [comment]
Thank you for your effort. 

> added the following snippet to the README which should help anyone

It should definitely help.

> I may poke around and see how hard it would be to get j2cl compiles working again. HTH

It would be very appreciated, the j2cl maven plugin seems to be quite matured right now.
